const insults = {
// Basic Categories
classic: [
	"You aren't your best friends best friend",
	"You're as sharp as a marble and twice as dense.",
	"Your wit's so slow, it takes you an hour to cook minute rice.",
	"You're about as useful as a chocolate teapot in a dragon's hoard.",
	"You bring everyone down to your level—and that's a tragic place to be.",
	"Your brain's on permanent vacation but your mouth never stops working.",
	"You're a walking contradiction wrapped in a disaster, tied with failure.",
	"You have the charisma of a damp rag soaked in disappointment.",
	"If ignorance is bliss, you must be the happiest fool in the multiverse.",
	"You have all the grace of a drunk kobold in a pottery shop.",
	"Your presence inspires nothing but pity and secondhand embarrassment.",
	"You're proof that natural selection occasionally takes sick days.",
	"Your family tree must be a cactus because everyone on it is a prick.",
	"You're the reason warning labels exist on obviously dangerous things.",
	"If brains were dynamite, you wouldn't have enough to blow your nose.",
	"You're like a broken pencil—completely pointless.",
	"Your birth certificate is an apology letter from the condom factory.",
	"You're not stupid, you just have bad luck thinking.",
	"You're the human equivalent of a participation trophy—awarded for just showing up.",
	"If you were any more inbred, you'd be a sandwich.",
	"You're living proof that evolution can go in reverse.",
	"Your intellect is as fake as a three-gold coin.",
	"You're about as bright as a black hole and twice as dense.",
	"You have the personality of wet cardboard—and that's insulting to cardboard.",
	"You're the reason gods created alcohol—to help people forget you exist.",
	"Your existence is like a typo in the book of life—embarrassing and unwanted.",
	"You're what happens when mediocrity sets its sights too high.",
	"If ignorance is bliss, you must be orgasmic.",
	"You're the kind of person who would get lost in their own thoughts—if they had any.",
	"You're about as useful as a screen door on a submarine.",
	"Your face could stop a sundial—permanently.",
	"You're like a coin—two-faced and worthless.",
	"If stupidity was a crime, you'd be serving life without parole.",
	"You're the reason people believe in reincarnation—nobody could get that unlucky in just one life.",
	"You have the depth of a puddle and the personality to match.",
	"You're what happens when someone orders intelligence and gets the knockoff version.",
	"Your mother should have swallowed you.",
	"You're like a software update—nobody wants you, but you keep showing up anyway.",
	"If you were any less intelligent, we'd have to water you twice a week.",
	"You're the human equivalent of a typo—everyone notices you, but nobody wants you there.",
	"Your gene pool could use some chlorine.",
	"You're about as helpful as a chocolate fireguard.",
	"If you had a brain, you'd be dangerous—thankfully, we're all safe.",
	"You're the reason people invented the phrase 'it could be worse'.",
	"You have the charm of a rusty nail and the intelligence of the hammer that hit it.",
	"You're like a broken clock—wrong most of the time, and annoying all of the time.",
	"If you were any more dense, you'd collapse into a black hole of disappointment.",
	"You're the human equivalent of a Monday morning—nobody wants to deal with you.",
	"Your existence is like a bad joke—it goes on too long and nobody laughs.",
	"You're what happens when a village loses its idiot—they send out a search party for you.",
	"If you were any more useless, you'd be a politician's campaign promise.",
],
performance: [
	"You sound like a cat strangling a bagpipe in a thunderstorm.",
	"Your rhythm's so bad even tone-deaf goblins cover their ears.",
	"You couldn't carry a tune if it came with handles and instructions.",
	"Your voice could clear a packed tavern faster than a fire spell.",
	"You play with all the passion of a sleeping slug.",
	"Your songs are the reason bards have a bad reputation.",
	"Even the tavern rats flee when you start performing.",
	"Your dancing is more hazardous than a gelatinous cube.",
	"You'd make a stone gargoyle weep—from sheer embarrassment.",
	"Your lute filed a restraining order against your fingers.",
],

age_young: [
	"You've got the energy of a caffeinated pixie but none of the wisdom.",
	"Your experience bar is still loading—very slowly.",
	"You're a baby dragon with paper wings and delusions of grandeur.",
	"Your armor's still got the price tags on it, doesn't it?",
	"Your youthful arrogance would be cute if it weren't so pathetic.",
	"You're a fledgling trying to soar with eagles and failing spectacularly.",
	"You stumble through adventures like a toddler in platemail.",
	"You've got the tactical awareness of a goblin with a shiny rock.",
	"You're a sapling pretending to be an ancient oak—and fooling no one.",
	"Your character sheet looks like it was filled out in crayon.",
],

age_middle: [
	"You're at that awkward age where your best days mock your current ones.",
	"You're the adventuring equivalent of stale tavern bread—past your prime.",
	"You're old enough to know better but young enough to fail anyway.",
	"Your midlife crisis armor is showing, and it's not flattering.",
	"You've got the enthusiasm of a bard who forgot their instrument at home.",
	"You're stuck between 'experienced' and 'washed up' with no map out.",
	"You're like a war horse past its prime but too stubborn to retire.",
	"Your glory days are behind you—way behind you.",
	"You're desperately clinging to relevance like a barnacle on a sinking ship.",
	"You've aged like cheap wine—poorly and with regret.",
],

age_old: [
	"You're so ancient, your first sword was carved from dinosaur bone.",
	"Your breath smells like the tomb you're destined for.",
	"You've collected more dust than a forgotten library.",
	"Your memory has more holes than a giant's fishing net.",
	"You're old enough to have given advice to legendary heroes—bad advice.",
	"You move with all the speed of continental drift.",
	"Your wrinkles have achieved their own geological status.",
	"You make skeletons look youthful and vibrant by comparison.",
	"You were ancient when the gods were still taking apprenticeships.",
	"Your wisdom is as faded as your eyesight and twice as useless.",
],

gender_male: [
	"You strut like a peacock with molting feathers.",
	"Your machismo is compensating for everything you lack.",
	"You talk tough but fight like you're swatting flies.",
	"Your beard can't hide your weak jawline or weaker character.",
	"You flex muscles you don't have to impress people who don't care.",
	"Your roar sounds like a kitten asking for milk.",
	"You swing your sword like you're afraid it might swing back.",
	"Your bravado crumbles faster than a stale biscuit.",
	"You're all bluster and no backbone.",
	"Your ego writes checks your abilities can't cash.",
],

gender_female: [
	"You sparkle like fool's gold—pretty but worthless.",
	"Your drama could power a small kingdom's theater district.",
	"You wield charm like a broken wand—ineffectively.",
	"Your smile hides all the competence you're missing.",
	"You flutter around problems instead of solving them.",
	"Your grace is as artificial as your confidence.",
	"You're sugar-coated poison with a side of disappointment.",
	"Your beauty is only matched by your complete lack of substance.",
	"You bat your eyelashes like they'll solve your problems—they won't.",
	"You're a tempest in a teacup, and the teacup is cracked.",
],

gender_nonbinary: [
	"You defy categories like a riddle no one wants to solve.",
	"Your identity shifts more than a doppelganger with commitment issues.",
	"You're a walking question mark in search of a decent answer.",
	"You confuse enemies and allies equally—mostly through incompetence.",
	"Your unpredictability would be an asset if it weren't so random.",
	"You're the wildcard that everyone wishes they could discard.",
	"You transcend boundaries mostly by stumbling through them.",
	"You're fluid like water—and just as likely to leak everywhere.",
	"Your complexity is admirable; your execution is not.",
	"You're the exception that proves every rule has loopholes.",
],

// Ability Score Insults
str: [
	"You flex like a wet noodle in a hurricane.",
	"Your biceps are purely decorative—and not very decorative at that.",
	"You lift spirits because you certainly can't lift anything else.",
	"A sickly halfling could arm-wrestle you into submission.",
	"Your muscles are as mythical as your combat effectiveness.",
	"You throw punches like you're underwater and wearing mittens.",
	"Your strength is so legendary—in that it's completely fictional.",
	"You break more promises than bones in combat.",
	"Your power is inversely proportional to your actual strength.",
	"You're living proof that size doesn't matter—neither does strength, apparently.",
	"Your grip strength couldn't open a jar of pickles if your life depended on it.",
	"You swing your weapon like you're afraid it might swing back.",
	"Your mighty thews are more like mighty wheeze.",
	"You punch with all the force of a gentle summer breeze.",
	"Your strength stat was clearly a typo—they meant to put it under weaknesses.",
	"You lift weights and the weights file a complaint for harassment.",
	"Your battle cry sounds like you're asking for help moving furniture.",
	"You're so weak, your shadow refuses to follow you uphill.",
	"Your muscles have the consistency of overcooked pasta.",
	"You bench press your own insecurities—which isn't much weight.",
	"Your handshake feels like a dying fish saying goodbye.",
	"You break a sweat trying to break bad habits.",
	"Your strength training consists of carrying emotional baggage.",
	"You crush your enemies' expectations—by setting them incredibly low.",
	"Your mighty roar sounds like a mouse clearing its throat.",
	"You wield weapons with all the authority of a suggestion box.",
	"Your physical prowess peaked when you opened that really tight bottle cap last year.",
	"You're built like a twig that gave up on becoming a branch.",
	"Your power lifting involves lifting people's spirits through pity.",
	"You throw your weight around, but there isn't much to throw.",
	"Your strength is legendary among communities of elderly librarians.",
	"You arm wrestle like you're afraid of winning—or trying.",
	"Your combat stance looks like you're perpetually asking for a hug.",
	"You deliver devastating blows to your own reputation.",
	"Your might makes right—if right means completely wrong.",
	"You're so weak, your sword carries you into battle.",
	"Your crushing grip couldn't crush grapes for wine.",
	"You flex and people mistake it for a mild tremor.",
	"Your strength comes in handy when you need to lift people's expectations—very slightly.",
	"You're built like a scarecrow that lost an argument with the wind.",
	"Your powerful strikes land with all the impact of constructive criticism.",
	"You wrestle with concepts better than you wrestle with anything physical.",
	"Your muscle definition is about as clear as your combat strategy.",
	"You're strong in all the ways that don't matter in a fight.",
	"Your physical training regimen consists mainly of mental gymnastics.",
	"You lift heavy things—like the burden of everyone's disappointed expectations.",
	"Your strength is inspirational—it inspires others to work out more.",
	"You're built like a question mark—confusing and slightly bent.",
	"Your raw power is so raw it's practically still alive and running away.",
	"You break things accidentally because your weakness is so surprising, it catches objects off guard.",
],

dex: [
	"Your reflexes are slower than a hibernating bear.",
	"You trip over shadows and apologize to the ground.",
	"Your agility is an elaborate practical joke the gods are playing.",
	"You dodge attacks by accidentally falling into them.",
	"Your stealth consists of a series of loud apologies.",
	"You move with all the grace of a landslide in platemail.",
	"Your nimbleness is purely theoretical—very theoretical.",
	"You fumble so consistently it's almost a talent.",
	"Your coordination is what happens when chaos meets incompetence.",
	"You make statues look positively acrobatic by comparison.",
	"Your balance is worse than a drunk elephant on ice skates.",
	"You stumble through life like it's an obstacle course designed by your enemies.",
	"Your hand-eye coordination is more like hand-everywhere-but-eye coordination.",
	"You dance like you're being attacked by invisible wasps—and losing.",
	"Your acrobatic skills peaked when you learned to walk—barely.",
	"You dodge like you're moving through invisible molasses.",
	"Your stealth makes a marching band seem subtle by comparison.",
	"You move with the fluid grace of chunky peanut butter.",
	"Your quickdraw is so slow, your weapon rusts before you unsheathe it.",
	"You're so clumsy, you trip over wireless connections.",
	"Your footwork resembles a seizure having an identity crisis.",
	"You sneak like a one-legged cat in a sandbox—loudly and unsuccessfully.",
	"Your reaction time is measured with a calendar, not a stopwatch.",
	"You catch thrown objects with your face—consistently.",
	"Your parkour consists mainly of spectacular face-plants.",
	"You're so uncoordinated, you miss the ground when you fall.",
	"Your sleight of hand is more like obvious-of-hand-while-apologizing.",
	"You move through crowds like a bull in a china shop having a nervous breakdown.",
	"Your gymnastic abilities make sloths look like Olympic athletes.",
	"You fumble with lock picks like you're afraid they might actually work.",
	"Your climbing skills are what gravity uses as a personal insult.",
	"You sidestep attacks by stepping directly into them—creatively.",
	"Your agility training consists mainly of falling down more gracefully.",
	"You're so clumsy, you make banana peels jealous of your slip-ups.",
	"Your stealth mode is louder than most people's normal walking.",
	"You catch arrows with your armor—usually by accident.",
	"Your balance beam performance would make a tightrope walker weep.",
	"You move like you're permanently stuck in slow motion during an earthquake.",
	"Your dexterous fingers are about as dexterous as frozen sausages.",
	"You tumble like a washing machine full of bricks going down stairs.",
	"Your evasion technique involves running directly into danger while apologizing.",
	"You're so unsteady, you make drunk sailors look like ballet dancers.",
	"Your precision strikes hit everything except what you're aiming for.",
	"You thread needles by stabbing the general vicinity repeatedly.",
	"Your cat-like reflexes belong to a cat that's been dead for several days.",
	"You slip on perfectly dry surfaces just to keep people guessing.",
	"Your fine motor control makes jackhammers look delicate.",
	"You're so uncoordinated, you trip over things that aren't there.",
	"Your agility is what happens when grace takes an extended vacation.",
	"You make turtles look like speed demons with coordination issues.",
],

con: [
	"You're frailer than parchment in a rainstorm.",
	"Your constitution was clearly an afterthought in your creation.",
	"You get winded from passionate speeches about your own weakness.",
	"Your immune system filed for unemployment years ago.",
	"You're one strong breeze away from total collapse.",
	"Your stamina makes glass look durable.",
	"You catch diseases that haven't been discovered yet.",
	"Your heartbeat sounds like a stuttering sparrow.",
	"You're allergic to physical exertion and mental effort.",
	"Your blood type is 'barely there' with a splash of 'questionable'.",
	"You're so frail, you break bones just thinking about exercise.",
	"Your endurance peaked when you learned to breathe—barely.",
	"You get tired from watching other people work out.",
	"Your health is as fragile as your ego and twice as problematic.",
	"You're built like a house of cards in a tornado shelter.",
	"Your constitution is what happens when durability goes on permanent vacation.",
	"You catch cold from looking at ice cubes.",
	"Your stamina bar is permanently empty and glitched.",
	"You're so weak, your pulse barely registers as a suggestion.",
	"Your immune system is what germs use as a vacation resort.",
	"You get exhausted from vigorous thinking—which explains a lot.",
	"Your physical resilience is purely theoretical—very theoretical.",
	"You're so delicate, you make flower petals look robust.",
	"Your constitution is what other people use as a worst-case scenario.",
	"You tire yourself out getting tired.",
	"Your health points are measured in negative numbers.",
	"You're allergic to your own existence—and it shows.",
	"Your endurance is legendary among people who've never exercised.",
	"You get winded from passionate disagreements about your weakness.",
	"Your body is a temple—specifically, a temple that's been abandoned and falling apart.",
	"You're so frail, your shadow refuses to follow you uphill.",
	"Your constitution is what happens when fortitude calls in sick permanently.",
	"You catch diseases from reading about them in books.",
	"Your stamina makes elderly librarians look like marathon runners.",
	"You're built like a soap bubble in a thunderstorm.",
	"Your physical condition is what warranty policies use as exclusions.",
	"You get exhausted from dreams about exercise.",
	"Your health is held together with hope and medical intervention.",
	"You're so weak, you make wet tissue paper look sturdy.",
	"Your constitution is what other constitutions use as cautionary tales.",
	"You break out in hives when exposed to the concept of physical activity.",
	"Your endurance is measured in moments, not minutes.",
	"You're so frail, you get bruised by strongly worded letters.",
	"Your immune system is what viruses recommend to their friends.",
	"You tire from the effort of being tired.",
	"Your physical resilience is what manufacturers use to test their most delicate products.",
	"You're built like a dandelion in a hurricane—and less durable.",
	"Your constitution makes paper cuts look like major injuries—to you.",
	"You get winded from heated discussions about your lack of stamina.",
	"Your health is so fragile, it comes with its own insurance policy—and high premiums."
],

int: [
	"You couldn't spell 'intelligence' if it was tattooed on your forehead.",
	"Your thoughts move slower than a philosophical zombie.",
	"You make rocks seem scholarly by comparison.",
	"Your brain operates on a part-time schedule—very part-time.",
	"You couldn't find your way out of a paper bag with a map and guide.",
	"Your intellect is what happens when wisdom goes on permanent vacation.",
	"You think deep thoughts—unfortunately, they're puddle-deep.",
	"Your IQ could be expressed as a negative number and still be too generous.",
	"You're proof that consciousness is just a suggestion, not a requirement.",
	"Your mind is a steel trap—rusted shut and forgotten in a basement.",
	"You have the intellectual capacity of a particularly dim candle—one that's been blown out.",
	"Your brain cells are on strike and have been for several decades.",
	"You think outside the box because you can't figure out how to get inside it.",
	"Your cognitive abilities peaked when you learned to breathe—and that was clearly a struggle.",
	"You're what happens when evolution decides to take a sick day.",
	"Your thought process is like watching paint dry—except paint eventually finishes.",
	"You have the mental agility of a sedated sloth with commitment issues.",
	"Your reasoning skills make circular logic look straightforward.",
	"You're living proof that the brain is optional equipment for some people.",
	"Your intellectual depth can be measured with a ruler—a very short ruler.",
	"You think so slowly that your ideas arrive pre-expired.",
	"Your mental capacity is what other people use as a unit of measurement for emptiness.",
	"You're the reason they put instructions on shampoo bottles—and you still get confused.",
	"Your brain is like a browser with 47 tabs open—none of them working properly.",
	"You have the problem-solving skills of a goldfish with amnesia.",
	"Your logic is so flawed it needs its own warranty and customer service department.",
	"You're what happens when stupidity achieves sentience and decides to go public.",
	"Your mental processing speed makes dial-up internet look lightning-fast.",
	"You think critically about as well as you think uncritically—which is not at all.",
	"Your intellectual curiosity died of boredom trying to find something to be curious about.",
	"You have the analytical skills of a magic 8-ball that's been shaken too hard.",
	"Your brain is like a computer running on Windows 95—slow, unreliable, and prone to crashing.",
	"You're the human equivalent of a 404 error—not found, and probably never was.",
	"Your thought patterns are what chaos theory uses as an example of true randomness.",
	"You have the retention capacity of a sieve made of swiss cheese.",
	"Your mental faculties are on permanent vacation in a place that doesn't exist.",
	"You're so intellectually challenged that riddles tell jokes about you.",
	"Your brain is like a library where all the books are blank and the librarian gave up.",
	"You have the learning curve of a flat line drawn by someone with severe hand tremors.",
	"Your cognitive function is what happens when thinking goes into witness protection.",
	"You're the reason they invented the phrase 'bless your heart'—someone had to take pity.",
	"Your mental gymnastics consist entirely of falling off the parallel bars of logic.",
	"You have the intellectual horsepower of a hamster on a broken wheel.",
	"Your brain is like a smartphone with no signal, no battery, and a cracked screen.",
	"You think with all the clarity of muddy water in a tornado.",
	"Your reasoning ability is what other people use to feel better about their own mistakes.",
	"You're living proof that intelligence is not uniformly distributed across the population.",
	"Your mental acuity is sharper than a bowling ball and twice as dense.",
	"You have the intellectual presence of a absent-minded professor who forgot to show up to his own absence.",
	"Your brain is like a GPS that's been dropped in a blender—it knows where it's supposed to go, but all the directions are scrambled."
];

wis: [
	"Your insight reads like a blank scroll written in invisible ink.",
	"You have the perception of a blindfolded mole in a sensory deprivation chamber.",
	"Your wisdom is what happens when experience meets a brick wall.",
	"You couldn't find water in an ocean with a diving bell.",
	"Your intuition is about as reliable as a chocolate sword.",
	"You mistake obvious traps for welcome mats on a regular basis.",
	"Your judgment is so poor, even bad decisions feel sorry for you.",
	"You have the street smarts of a sheltered houseplant.",
	"Your awareness operates on a 'need to never know' basis.",
	"You're so oblivious, you make blindness look perceptive."
],

cha: [
	"Your charm is as appealing as a rotting fish in summer heat.",
	"You have the social grace of a rabid owlbear at a tea party.",
	"Your personality has all the magnetism of wet leather.",
	"You inspire others—to leave the room as quickly as possible.",
	"Your presence lowers the collective charisma of everyone nearby.",
	"You could make a succubus take a vow of celibacy.",
	"Your smooth talk sounds like sandpaper on a chalkboard.",
	"You're as persuasive as a tax collector at a funeral.",
	"Your charisma is so low, mirrors refuse to reflect you.",
	"You make social awkwardness look like a refined art form."
],

// Creature Type Insults
undead: [
"You're so lifeless, even zombies find you boring.",
"Your shambling makes other undead embarrassed to be dead.",
"You smell worse than a ghoul's dinner leftovers.",
"Even necromancers think twice before raising something like you.",
"You're what happens when death itself makes a mistake.",
"Your moaning is less terrifying, more irritating.",
"You're the reason people aren't afraid of the undead anymore.",
"Your existence is an insult to the concept of unlife.",
"You make vampires consider switching to holy water.",
"Even other undead cross to the other side of the street to avoid you."
],

fiend: [
"You're the disappointment Hell sends when it's feeling passive-aggressive.",
"Your evil is so mediocre, even imps file complaints.",
"You have all the menace of a strongly worded letter from the afterlife.",
"Your infernal nature got lost in translation—and shipping.",
"You're what happens when damnation comes with a money-back guarantee.",
"Your wickedness is more 'mildly inconvenient' than 'terrifyingly evil'.",
"You're the participation trophy of the demonic hierarchy.",
"Your corruption is so weak, it couldn't spoil milk.",
"You make lawful good paladins question if evil is even real.",
"Your dark powers are more like dimly lit suggestions."
],

celestial: [
"Your halo slipped and fell off—probably for the best.",
"You radiate holiness like a broken lamp radiates light—barely and poorly.",
"Your divine nature must have gotten lost in the mail.",
"You're what happens when heaven settles for 'good enough'.",
"Your righteousness is as convincing as a tiefling preacher.",
"You glow with all the divine majesty of a dying firefly.",
"Your blessing feels more like a mild suggestion from above.",
"You're the clearance rack angel no one wanted to buy.",
"Your wings are purely ornamental—like your moral authority.",
"You make other celestials wonder if they're in the wrong business."
],

beast: [
"You have all the predatory instincts of a domesticated hamster.",
"Your roar sounds like a kitten with a head cold.",
"You're the runt of a litter that should never have been born.",
"Your hunting skills make vegetarian rabbits look fierce.",
"You're about as wild as a goldfish in a teacup.",
"Your natural instincts apparently include 'fail spectacularly'.",
"You make house cats look like apex predators.",
"Your pack rejected you for lowering the average intelligence.",
"You're what evolution would undo if it had an eraser.",
"Your survival instincts are apparently optional equipment."
],

dragon: [
"Your hoard consists entirely of participation trophies and regret.",
"You breathe fire like a broken bellows—mostly smoke and disappointment.",
"Your scales are duller than a politician's campaign promises.",
"You fly with all the grace of a falling boulder with delusions.",
"Your roar inspires more pity than terror in local villages.",
"You're the reason kobolds have trust issues with their 'masters'.",
"Your treasure room is just an empty cave with an echo problem.",
"You make wyrmlings look ancient and wise by comparison.",
"Your draconic pride is built on a foundation of sand and wishful thinking.",
"You're living proof that not all dragons are created equal—or competent."
],

aberration: [
"You're what nightmares have when they want to feel better about themselves.",
"Your existence violates several laws of nature—and good taste.",
"You make other aberrations question their life choices.",
"Your alien intelligence is emphasis on 'alien,' light on 'intelligence'.",
"You're a cosmic joke that forgot to be funny.",
"Your otherworldly nature is more 'other-worthless'.",
"You bend reality around you—mostly by being too dense to notice it.",
"Your sanity-blasting presence mostly just causes mild headaches.",
"You're the reason the Far Realm has quality control issues.",
"Your tentacles are the least disturbing thing about you."
],

construct: [
"You were assembled by someone who clearly lost the instruction manual.",
"Your gears grind louder than your thought processes.",
"You're powered by disappointment and fueled by malfunction.",
"Your creator must have been having an off century when they made you.",
"You're less 'precisely engineered' and more 'cobbled together with hope'.",
"Your programming has more bugs than a spider farm.",
"You clank like a one-man percussion section having a breakdown.",
"You're the factory recall that never got processed.",
"Your artificial intelligence is about as artificial as it gets.",
"You make broken clockwork look like precision engineering."
],

elemental: [
"You're the weakest force of nature since light drizzle.",
"Your elemental fury is more like elemental mild annoyance.",
"You control the elements about as well as you control your own destiny—poorly.",
"Your primal power feels more like a gentle suggestion from the universe.",
"You're what happens when the elements phone it in.",
"Your connection to nature has been permanently disconnected.",
"You embody the raw power of a slightly warm breeze on a calm day.",
"Your elemental form is what the elements look like when they give up.",
"You make other elementals question their commitment to the natural order.",
"Your power over the elements extends to mild weather observations."
],

fey: [
"Your magic is more 'tragic' than 'fey'.",
"You're what happens when whimsy meets incompetence and has children.",
"Your otherworldly beauty is definitely from another world—a much less attractive one.",
"You grant wishes like a broken genie—technically, but regrettably.",
"Your fairy tale ending involves everyone walking away disappointed.",
"You're the reason mortals stopped believing in magic.",
"Your enchantments are about as effective as your personality—not at all.",
"You dance like you're having a seizure in a flower garden.",
"Your connection to nature is what's killing all the plants around here.",
"You make other fey creatures consider relocating to the material plane."
],

giant: [
"You're large and in charge of absolutely nothing important.",
"Your size is the only impressive thing about you—and even that's debatable.",
"You have the intellectual capacity of a particularly dim boulder.",
"Your footsteps announce your arrival and your incompetence simultaneously.",
"You're living proof that bigger isn't always better—or even adequate.",
"Your club is smarter than you are, and it's a piece of wood.",
"You make ogres look sophisticated and cultured by comparison.",
"Your strength is matched only by your inability to use it effectively.",
"You're the reason people stopped fearing giants and started pitying them.",
"Your legendary status is 'legendarily disappointing'."
],

monstrosity: [
"You're an abomination that makes other abominations feel better about themselves.",
"Your multiple parts clearly don't add up to a functioning whole.",
"You're what happens when nature has a bad day and worse judgment.",
"Your existence is a biological punchline to a joke nobody wanted to hear.",
"You make chimeras look well-designed and purposeful.",
"Your twisted form is matched only by your twisted logic.",
"You're the reason evolution occasionally takes steps backward.",
"Your unnatural appearance is the least unnatural thing about you.",
"You're living proof that some experiments should never leave the laboratory.",
"Your monstrous nature is mostly just monster-ously disappointing."
],

ooze: [
"You have all the personality of primordial soup—and less flavor.",
"Your acidic nature couldn't dissolve a sugar cube in warm water.",
"You flow like molasses uphill in winter—slowly and pointlessly.",
"Your gelatinous form is as appealing as it sounds—which is not at all.",
"You're the reason people don't trust things without defined edges.",
"Your digestive processes are more interesting than your personality.",
"You leave a trail of disappointment wherever you slither.",
"Your shapeless existence mirrors your shapeless thoughts perfectly.",
"You make mud puddles look structured and purposeful.",
"Your presence sticks to everything like regret after a bad decision."
],

plant: [
"You're the weed in the garden of life—and not even a useful one.",
"Your photosynthesis is as efficient as your combat ability—barely functional.",
"You have all the mobility of dead tree bark and half the usefulness.",
"Your roots run shallow—like your thinking.",
"You're what happens when nature settles for 'barely adequate'.",
"Your growth is stunted by your own incompetence.",
"You make cacti look cuddly and inviting by comparison.",
"Your bark is worse than your bite—which isn't saying much.",
"You're the reason gardeners carry pruning shears—as weapons.",
"Your seasonal changes are from 'disappointing' to 'more disappointing'."
],

humanoid: [
"You're the baseline that makes everyone else look exceptional.",
"Your humanity is showing—and it's not your best feature.",
"You're so average, you make mediocrity look like an achievement.",
"Your potential peaked at birth and has been declining ever since.",
"You're what happens when the universe runs out of interesting ideas.",
"Your mundane existence makes watching paint dry seem thrilling.",
"You're the control group in the experiment of life—and you're failing.",
"Your common sense is neither common nor sensible.",
"You make other humanoids question their species classification.",
"Your ordinary nature is extraordinarily disappointing."
],

// Class-Specific Insults
fighter: [
"You swing your sword like you're afraid it might hit something important.",
"Your combat technique resembles interpretive dance—badly performed interpretive dance.",
"You wear armor to protect your feelings more than your body.",
"Your battle cry sounds like a question—a very uncertain question.",
"You charge into combat like you're looking for the exit.",
"Your weapon proficiency is more like weapon incompetency.",
"You fight with all the tactical awareness of a concussed goblin.",
"Your defensive stance is indistinguishable from cowering.",
"You make other fighters embarrassed to share the same class.",
"Your combat experience consists mostly of combat inexperience."
],

rogue: [
"You sneak like a marching band during an earthquake.",
"Your stealth is legendary—in that it's completely fictional.",
"You pick locks about as well as you pick your battles—poorly.",
"Your backstab is more like a polite tap on the shoulder.",
"You're so sneaky, everyone sees you coming from three counties away.",
"Your thieves' cant is more like thieves' can't.",
"You disable traps by triggering them—repeatedly.",
"Your slight of hand is more like obvious of hand.",
"You hide in shadows that make you more visible than standing in sunlight.",
"Your criminal contacts avoid you because you're bad for business."
],

wizard: [
"Your spells fizzle more often than a wet torch in a thunderstorm.",
"You study magic like you're allergic to understanding it.",
"Your spellbook is mostly filled with grocery lists and doodles.",
"You cast spells with all the precision of a blindfolded dart thrower.",
"Your arcane focus is clearly out of focus—permanently.",
"You make cantrips look like high-level magic by comparison.",
"Your familiar refuses to acknowledge your existence in public.",
"You memorize spells like you memorize excuses—half-heartedly.",
"Your magical research consists of copying other people's homework—badly.",
"You make other wizards question the intelligence requirement for the class."
],

cleric: [
"Your prayers bounce back marked 'return to sender'.",
"Your divine connection has been permanently disconnected for non-payment.",
"You channel divinity like you channel confidence—not at all.",
"Your holy symbol is embarrassed to be associated with you.",
"You turn undead about as effectively as you turn pages in a book—clumsily.",
"Your healing touch makes conditions worse through sheer incompetence.",
"Your deity is considering switching to a different religion to avoid you.",
"Your sermons put even the gods to sleep.",
"You bless people and they immediately start looking for curse removal.",
"Your divine magic is more 'divine comedy'—emphasis on comedy."
],

barbarian: [
"Your rage is more like mild irritation with anger management issues.",
"You fight like you're afraid of breaking a nail—if you had any.",
"Your primal instincts are primarily focused on avoiding responsibility.",
"You charge into battle like you're looking for a bathroom.",
"Your berserker fury resembles a toddler's temper tantrum—less effective, more embarrassing.",
"Your tribal heritage disowned you for bringing down property values.",
"You swing your weapon like you're swatting flies—very slow, very tired flies.",
"Your intimidating presence makes people feel sorry for you instead of afraid.",
"You make other barbarians consider taking up accounting instead.",
"Your battle frenzy is more like battle confusion with a side of panic."
],

bard: [
"You perform like you're trying to clear the room—and succeeding.",
"Your music makes people nostalgic for complete silence.",
"You inspire others—to take up different hobbies, far away from you.",
"Your bardic knowledge consists mainly of things nobody wanted to know.",
"You sing like you're auditioning for the role of 'worst bard ever' and nailing it.",
"Your charisma is as fictional as the stories you tell about your adventures.",
"You make other bards consider switching to mime work.",
"Your performances are the reason taverns started charging cover charges—to keep you out.",
"Your lute is plotting its escape to a more competent musician.",
"Your artistic expression expresses mainly incompetence and poor judgment."
],

paladin: [
"Your oath is as binding as a suggestion written in disappearing ink.",
"You smite evil about as effectively as you smite your own credibility.",
"Your holy aura is more 'mildly blessed' than 'divinely radiant'.",
"Your righteous fury is neither particularly righteous nor particularly furious.",
"You lay on hands like you're afraid of actually touching people.",
"Your divine sense is clearly malfunctioning—permanently.",
"You champion justice like you champion lost causes—poorly and with little hope.",
"Your mount keeps trying to find a new rider—any new rider.",
"You make other paladins question their commitment to goodness.",
"Your divine favor feels more like divine indifference with a hint of disappointment."
],

druid: [
"You commune with nature and nature files a restraining order.",
"Your wild shape is more 'mild disappointment' than 'wild anything'.",
"You speak with animals and they pretend not to understand you.",
"Your connection to the natural world is what's killing all the plants around here.",
"You shape-shift like you're allergic to having a consistent form.",
"Your animal companions keep looking for the exit.",
"You're one with nature—unfortunately, nature wants a divorce.",
"Your druidcraft is more like druid-can't.",
"You make other druids consider careers in urban planning.",
"Your natural magic is unnaturally disappointing."
],

sorcerer: [
"Your innate magic is more 'innately disappointing' than 'innately powerful'.",
"You cast spells like you're afraid they might actually work.",
"Your bloodline is embarrassed to be associated with your magical ability.",
"Your wild magic surges are wilder than your actual spells—which isn't saying much.",
"You channel raw magical energy like you channel success—not at all.",
"Your metamagic makes magic more meta and less magic.",
"You're proof that some bloodlines should end with you.",
"Your sorcerous origin wishes it had chosen someone else.",
"You manipulate magical energy like you manipulate social situations—awkwardly and with poor results.",
"Your spellcasting ability is more like spell-catastrophe ability."
],

warlock: [
"Your patron is considering breaking your contract for non-performance.",
"You serve a greater power—poorly and with obvious reluctance.",
"Your eldritch blast is more 'eldritch disappointment'.",
"Your pact weapon is embarrassed to be wielded by you.",
"You channel otherworldly power like you channel confidence—not at all.",
"Your patron keeps screening your calls.",
"You make deals with cosmic entities and somehow still end up with the short end.",
"Your invocations are more like involuntary reactions to your own incompetence.",
"You're the reason patrons started adding performance clauses to pacts.",
"Your connection to your patron is about as reliable as your everything else."
],

monk: [
"Your inner peace is more like inner chaos with a meditation app.",
"You achieve enlightenment like you achieve everything else—not at all.",
"Your martial arts look like you're fighting invisible bees—and losing.",
"You find your center and immediately lose it again.",
"Your ki flows like molasses uphill in winter—slowly and against its will.",
"You practice mindfulness and somehow become less mindful.",
"Your unarmored defense is more like unarmed surrender.",
"You deflect missiles back to where they came from—your own incompetence.",
"Your way of the elements involves getting in their way—unsuccessfully.",
"You make other monks consider taking vows of silence to avoid talking to you."
],

ranger: [
"You track animals and they file missing person reports on you.",
"Your favored enemies are favored because they consistently defeat you.",
"You navigate the wilderness like you navigate social situations—badly and with frequent wrong turns.",
"Your animal companion is your only friend—and it's reconsidering.",
"You hunt monsters and they hunt better employment opportunities.",
"Your survival skills mostly involve barely surviving your own decisions.",
"You're a guide to getting lost more efficiently.",
"Your archery skills make storm troopers look like expert marksmen.",
"You commune with nature and nature asks you to leave.",
"Your ranger magic is more like ranger tragic."
],

// Race-Specific Insults
dragonborn: [
"Your draconic heritage must have gotten lost in the mail—several generations ago.",
"You breathe fire like a dragon with asthma—pathetically and rarely.",
"Your scales are duller than your conversation and half as interesting.",
"You roar like a kitten with a throat infection.",
"Your dragon ancestors are spinning in their hoards.",
"You have all the majesty of a lizard with delusions of grandeur.",
"Your breath weapon couldn't light a candle on a windless day.",
"You're what happens when dragon blood gets severely diluted.",
"Your draconic pride is built on a foundation of wishful thinking.",
"You make kobolds look like legitimate dragon descendants."
],

dwarf: [
"Your beard has more personality than you do—and it's not saying much.",
"You're shorter than your temper and twice as unpleasant.",
"Your ale tolerance is higher than your competence—which isn't hard.",
"You mine for gold and find only disappointment.",
"Your axe is sharper than your wit—and your axe is dull.",
"You're built like a boulder and about as useful in conversation.",
"Your clan disowned you for lowering their reputation.",
"You smell like a brewery that gave up on quality control.",
"Your craftsmanship is what other dwarves use as cautionary examples.",
"You're the reason people stopped respecting dwarven work ethic."
],

elf: [
"Your grace is as artificial as your superiority complex.",
"You're older than dirt and somehow less mature.",
"Your longevity is wasted on your personality.",
"You float through life like you're afraid of actually touching it.",
"Your archery skills make other elves embarrassed to carry bows.",
"You're proof that immortality doesn't guarantee wisdom.",
"Your connection to nature is what's making all the trees wilt.",
"You dance like you're having a seizure in slow motion.",
"Your elven heritage is embarrassed to be associated with you.",
"You make humans grateful for their shorter lifespans—at least they don't have to put up with you as long."
],

gnome: [
"Your size matches your impact on the world—negligible.",
"You tinker with gadgets because you've given up on tinkering with your personality.",
"Your curiosity killed more than cats—it killed everyone's patience.",
"You're what happens when whimsy meets incompetence and has children.",
"Your inventions work about as well as your social skills—not at all.",
"You talk fast because you're afraid people will interrupt with better ideas.",
"Your small stature is matched only by your small achievements.",
"You make other gnomes consider relocating to different forests.",
"Your mechanical aptitude is purely theoretical—very theoretical.",
"You're living proof that good things don't always come in small packages."
],
goliath: [
"You're built like a mountain and about as intellectually stimulating.",
"Your size intimidates everyone except your own competence.",
"You compete with rocks for who can be more stone-faced and less useful.",
"Your tribal strength couldn't lift your own reputation.",
"You tower over others physically while they tower over you mentally.",
"Your endurance is legendary—legendarily boring to witness.",
"You climb mountains because even they're more interesting than your personality.",
"Your stone-like resilience extends to your stone-like thinking.",
"You're living proof that bigger doesn't mean better—or even adequate.",
"Your physical prowess is matched only by your intellectual weakness."
],

halfelf: [
"You're the worst of both worlds wrapped in identity crisis packaging.",
"You belong nowhere and prove it everywhere you go.",
"Your mixed heritage gave you mixed results—all disappointing.",
"You're too elven for humans and too human for elves—and too annoying for everyone.",
"Your dual nature is dually incompetent.",
"You're what happens when two great races accidentally create something mediocre.",
"Your versatility extends to being consistently disappointing in multiple ways.",
"You're caught between two worlds and failing in both.",
"Your identity crisis has an identity crisis.",
"You make pure breeds grateful for their genetic consistency."
],

halfling: [
"Your luck ran out before your first adventure began.",
"You're brave enough to be foolish and small enough to be ignored.",
"Your second breakfast is more impressive than your combat skills.",
"You're what happens when courage gets severely downsized.",
"Your nimbleness is matched only by your ability to avoid responsibility.",
"You throw stones because that's about your intellectual level.",
"Your size makes you hard to hit—unfortunately, your personality makes you easy to hate.",
"You're proof that good things come in small packages—except when they don't.",
"Your burrow is the only hole you haven't dug yourself into.",
"You make other halflings consider relocating to less embarrassing shires."
],

halforc: [
"You got the orc strength but missed the pickup for orc intelligence—which wasn't much to begin with.",
"Your rage issues have rage issues.",
"You're what happens when brutality meets stupidity and has children.",
"Your tusks are sharper than your wit—and your tusks are practically dull.",
"You grunt because forming complete sentences requires skills you don't possess.",
"Your orcish heritage is embarrassed to claim you.",
"You swing weapons like you're afraid they might actually connect.",
"Your intimidation factor is purely theoretical—like your combat effectiveness.",
"You're the reason people aren't afraid of half-orcs anymore.",
"Your dual nature is doubly disappointing."
],

human: [
"You're so painfully average, you make mediocrity look like an achievement.",
"Your potential peaked at conception and has been declining ever since.",
"You're the vanilla ice cream of adventurers—bland and easily replaced.",
"Your versatility extends to being consistently disappointing in multiple areas.",
"You're what other races point to when they want to feel superior.",
"Your ambition is matched only by your inability to achieve anything meaningful.",
"You're living proof that evolution sometimes takes coffee breaks.",
"Your short lifespan is a mercy to everyone else.",
"You adapt to new situations by failing in innovative ways.",
"You're the reason other races question the concept of equality."
],

tiefling: [
"Your infernal heritage couldn't heat a cup of tea on a summer day.",
"You're what happens when hell settles for 'barely adequate'.",
"Your demonic appearance is the most interesting thing about you—which isn't saying much.",
"Your tail has more personality than the rest of you combined.",
"You're proof that even corruption can be underwhelming.",
"Your horns are purely decorative—like your threatening demeanor.",
"You make devils reconsider their recruitment standards.",
"Your fire resistance doesn't extend to resisting complete failure.",
"You're the participation trophy of the infernal hierarchy.",
"Your dark heritage is embarrassed to be associated with your bright incompetence."
],

warforged: [
"You were built for a purpose—unfortunately, no one remembers what it was.",
"Your programming has more bugs than a spider farm in summer.",
"You're what happens when craftsmanship meets a tight deadline and lower standards.",
"Your creator clearly cut corners—and then cut more corners.",
"You malfunction so consistently it's become your primary function.",
"Your gears grind louder than your thought processes—which isn't hard.",
"You're the factory recall that never got processed.",
"Your artificial nature is obvious—no one would naturally be this disappointing.",
"You run on steam, powered by disappointment, and fueled by malfunction.",
"You make other constructs grateful they weren't assembled by your creator."
],

// Special Categories
avernus: [
"You're what Avernus spits out when even hell has standards.",
"Your presence makes the River Styx seem refreshing by comparison.",
"You're the reason demons started unionizing for better working conditions.",
"Even the Blood War takes coffee breaks when you show up.",
"Your incompetence is legendary throughout the Nine Hells—and that's saying something.",
"You make Zariel question her life choices—and she's a fallen angel.",
"Your failures echo through Avernus like the screams of the damned—but less musical.",
"You're what happens when the Abyss and the Nine Hells collaborate on a disappointment.",
"Devils use your combat record as a morale booster for their enemies.",
"You're the reason Avernus installed revolving doors—to get rid of you faster.",
"Your soul is so worthless, even devils refuse to make contracts with you.",
"You're the reason Tiamat stays locked in her prison—she's embarrassed to be associated with you.",
"Your battle tactics make lemures look like master strategists.",
"Even the lemures point and laugh when you stumble through their ranks.",
"You're what happens when damnation comes with a satisfaction-or-your-money-back guarantee.",
"Your torment is so pathetic, you make the damned souls feel better about their situations.",
"You fight like you're trying to get yourself banished from hell—and failing at that too.",
"Your screams of agony sound like a dying cat auditioning for a choir—unsuccessfully.",
"You make bone devils grateful they don't have to work with living disappointments.",
"Your infernal stench is what happens when brimstone meets complete failure.",
"You're the reason pit fiends started requiring performance reviews.",
"Your presence turns the Lake of Fire into a lukewarm puddle of disappointment.",
"You make chain devils reconsider their commitment to eternal torment.",
"Your combat prowess is so legendary, devils tell stories about it to make their children behave.",
"You're what happens when the Nine Hells outsource their incompetence.",
"Your war record reads like a comedy written by drunk imps.",
"You make barbed devils feel smooth and sophisticated by comparison.",
"Your tactical genius is why Avernus has a 'participant' trophy case.",
"You're the reason hell's army uses you as a cautionary tale—and a bad example.",
"Your infernal rage burns with all the intensity of a damp candle in a hurricane.",
"You make erinyes question their dedication to lawful evil—surely chaos would be more effective.",
"Your diabolic schemes have all the cunning of a kobold with a head injury.",
"You're what happens when even the Hells settle for 'good enough'—and then regret it.",
"Your presence makes the Iron City of Dis look like a vacation resort.",
"You fight with war machines that break down from sheer embarrassment.",
"Your infernal contracts are written in crayon and signed with regret.",
"You make horned devils consider filing their horns down to avoid the association.",
"Your battle cry sounds like a question mark followed by an apology.",
"You're the reason Avernus has mandatory performance improvement seminars.",
"Your diabolic nature is more 'mildly inconvenient' than 'eternally damning'.",
"You make the River Styx consider changing its name to avoid confusion with your reputation.",
"Your infernal heritage couldn't corrupt a saint having a bad day.",
"You're what happens when hell runs out of competent evil and starts improvising.",
"Your presence makes other devils nostalgic for the time before you existed.",
"You fight like you're afraid your weapons might accidentally work.",
"Your diabolic cunning is what other devils use as an example of what not to do.",
"You make succubi reconsider their career choices—surely accounting would be more fulfilling.",
"Your infernal corruption spreads like good news in hell—slowly and with limited effect.",
"You're the reason Asmodeus started delegating more responsibilities—to literally anyone else.",
"Your battle formations look like abstract art drawn by someone who's never seen a battle.",
"You make gelugons feel warm and fuzzy by comparison—which is deeply disturbing for everyone."
],
};


function getRandom(arr, count = 3) {
const shuffled = arr.slice().sort(() => 0.5 - Math.random());
return shuffled.slice(0, count);
}

function generateInsults() {
const category = document.getElementById('category').value;
let output = [];

if (insults[category]) {
output = getRandom(insults[category], 3);
} else {
output = ["Say something meaner. Try again!"];
}

document.getElementById('insultOutput').innerHTML = output.map(i => `<p>🗯️ ${i}</p>`).join('');
}
